name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GH_TOKEN }}
        issue-message: 'Dear new contributor, We are pleased to see your first issue on this repo. Hope to see more contributions from you. Kudos!'
        pr-message: 'Dear new contributor, We are pleased to see your first pull request on this repos. Hope to see more contributions from you. Kudos!'